### ISSUE TITLE
Would like to generate short-form empty elements

### ISSUE THREAD

**Issue by candlerb** [martinblech/xmltodict#100]
~~~
>>> xmltodict.unparse({"foo":None}, full_document=False)
u'<foo></foo>'
>>> xmltodict.unparse({"foo":{"@bar":"baz"}}, full_document=False)
u'<foo bar="baz"></foo>'
~~~

If would be nice to have an option to generate `<foo/>` and `<foo bar="baz"/>` respectively.

**Comment by itsgrimetime** [comment]
Would you be open to accepting a pull request that implements this? I am currently working on a project trying to generate XML for an application that treats <tag></tag> and <tag/> differently for some reason. While I am unhappy that this application has this behavior, it is closed source. I'd be willing to try to work on something that implements this, if you're open to it.

**Comment by itsgrimetime** [comment]
Nevermind! I just looked through the code and see that unparse takes short_emtpy_tags, this solves my problem - thanks!
