### ISSUE TITLE
Want to add more "docstring"

### ISSUE THREAD

**Issue by kmonsoor** [martinblech/xmltodict#102]
hello @martinblech, i am using using this nice little library for quite a while. I feel & would like to do some contribution back. 
As i am not that good coder to make something new, i want to start with documentation which i felt lack of as a user. If you agree, i want to know which way you prefer it?
 1. All suggested docstring / documentation on a single changelist / branch, or
 2. One-chunk of change in docs at a time ?

**Comment by martinblech** [comment]
Absolutely, @kmonsoor. `xmltodict` is certainly lacking on the documentation side and your contributions will be very welcome. I have no preference on doing it one way or another, just do it however you feel more comfortable and I'll be happy to review the Pull Requests. Thank you!

**Comment by kmonsoor** [comment]
thanks, @martinblech for your kind response.
in that case, i will go one-stub-at-a-time approach.
