### ISSUE TITLE
AttributeError: 'module' object has no attribute 'xmltodict'

### ISSUE THREAD

**Issue by rrajni** [martinblech/xmltodict#105]
import json
import xmltodict as xml
s = open("Status.xml").read()
d = xml.xmltodict(s)
json.dump(d['subway'][0]['line'],open("service_status.json",'w'))

Trying to run the above code for converting xml to json. But I am getting this error.
Traceback (most recent call last):
  File "L:/VISLZN/P1/PROG1.PY", line 6, in <module>
    d = xml.xmltodict(s)
AttributeError: 'module' object has no attribute 'xmltodict'

I am running 64 bit windows with Python 2.7 installed. Any help will be appreciated

**Comment by kmonsoor** [comment]
You should use like :
    
    d = xmltodict.parse(open("Status.xml"))

There is **nothing** like *xmldict.xmldict* you are trying to use. That's why you are getting the AttributeError.

**Comment by rrajni** [comment]
Thanks kmonsoor.
