### ISSUE TITLE
Namespace declarations in root element disappear on unparse

### ISSUE THREAD

**Issue by gwillden** [martinblech/xmltodict#106]
The unparse() method does not properly reserialize the namespace declarations into the XML string.
Please compare the output of the various calls below.  In the namespace-enabled case, the unparse method produces invalid XML because it fails to reserialize the "xmlns" attributes of the root element.

    import xmltodict
    import json

    xml = """
    <root xmlns="http://defaultns.com/"
          xmlns:a="http://a.com/"
          xmlns:b="http://b.com/">
      <x>1</x>
      <a:y>2</a:y>
      <b:z>3</b:z>
    </root>
    """

    namespaces = {"http://defaultns.com/":"root",
                  "http://a.com/":"a",
                  "http://b.com/":"b"}

    print(xml)
    nons = xmltodict.parse(xml)
    ns = xmltodict.parse(xml, process_namespaces=True, namespaces=namespaces)
    
    print("No Namespaces:")
    print(xmltodict.unparse(nons, pretty=True))
    
    print("\nWith Namespaces:")
    print(xmltodict.unparse(ns, pretty=True))  #The Namespace declarations in the root element disappear

Example Output:

    <root xmlns="http://defaultns.com/"
          xmlns:a="http://a.com/"
          xmlns:b="http://b.com/">
      <x>1</x>
      <a:y>2</a:y>
      <b:z>3</b:z>
    </root>
    
    No Namespaces:
    <?xml version="1.0" encoding="utf-8"?>
    <root xmlns="http://defaultns.com/" xmlns:a="http://a.com/" xmlns:b="http://b.com/">
            <x>1</x>
            <a:y>2</a:y>
            <b:z>3</b:z>
    </root>
    
    With Namespaces:
    <?xml version="1.0" encoding="utf-8"?>
    <root:root>
            <root:x>1</root:x>
            <a:y>2</a:y>
            <b:z>3</b:z>
    </root:root>

**Comment by gwillden** [comment]
It looks like the expat parser is not passing the xmlns attributes of the root element on to the startElement handler when operating in namespace mode.

If you add the following code to the end of the above example it will work around it.
**Note that this is extremely inefficient because you have to parse the file twice. Once with namespace handling disabled and once with it enabled.**

There must be a better way, but I don't know what it is right now.

    for key,value in nons['root'].items():
        if key.startswith('@xmlns'):
            ns['root'][key]=value
    
    print(xmltodict.unparse(ns, pretty=True))

Output

    <?xml version="1.0" encoding="utf-8"?>
    <root xmlns="http://defaultns.com/" xmlns:a="http://a.com/" xmlns:b="http://b.com/">
            <x>1</x>
            <a:y>2</a:y>
            <b:z>3</b:z>
    </root>

**Comment by asandvig** [comment]
Expat requires a separate handler for processing namespace declarations on elements. This is currently not implemented in `xmltodict`. A proposal to support this has been described in issue #110.

**Comment by martinblech** [comment]
@asandvig Thank you for your contribution. Could you please re-send it in pull request form so it's easier to review?
