### ISSUE TITLE
Is it possible to support comments?

### ISSUE THREAD

**Issue by KenetJervet** [martinblech/xmltodict#109]
I'd really like to have support for comments in lxml. It might be tricky especially for comments next to the root element.

**Comment by asandvig** [comment]
Yes, it's possible by implementing a comment handler for Expat (ref. [xmlparser.CommentHandler](https://docs.python.org/2/library/pyexpat.html#xml.parsers.expat.xmlparser.CommentHandler)).

However, one also needs to figure out how to represent comments in the returned dictionary. Something like a special `#comment` key, maybe?

**Comment by KenetJervet** [comment]
@asandvig `#comment` is the most natural key to use. But the comment may occur before a given node or after it, and there may be multiple comment nodes. For the comments between two nodes, which one should they belong to? Or maybe I'm being stupid.

**Comment by martinblech** [comment]
I'd be glad to review and merge a pull request if proposed.

**Comment by Dimama** [comment]
Hi, when this feature will be included in the release?

**Comment by ag-sd** [comment]
hi @martinblech  when will this feature be released? I do not see this in the current version of 0.12.0
