### ISSUE TITLE
Namespace declarations on elements are lost during parsing

### ISSUE THREAD

**Issue by asandvig** [martinblech/xmltodict#110]
Currently, `xmltodict` does not return any information about any namespace declarations that may have been present on the elements.

Expat does not treat these as regular attributes (as they are not part of the XML data, and are only considered useful to the XML parser itself) and they are therefore not included as attributes in the returned dictionary from `xmltodict.parse()` either.

To get access to the namespace declarations during Expat parsing, you must provide a "start namespace declaration" handler for Expat to call (ref. [xml.parsers.expat.xmlparser.StartNamespaceDeclHandler](https://docs.python.org/2/library/pyexpat.html#xml.parsers.expat.xmlparser.StartNamespaceDeclHandler)).

Here's a crude example of how `xmltodict` can be modified to include the namespace declarations as a named attribute (`@xmlns`) on the element where they are defined (the value of the attribute is an ordered dictionary of namespaces keyed by their prefix, as defined in the namespace declaration):

```diff
@@ -67,6 +67,7 @@ class _DictSAXHandler(object):
         self.strip_whitespace = strip_whitespace
         self.namespace_separator = namespace_separator
         self.namespaces = namespaces
+        self.namespace_declarations = OrderedDict()
 
     def _build_name(self, full_name):
         if not self.namespaces:
@@ -86,9 +87,15 @@ class _DictSAXHandler(object):
             return attrs
         return self.dict_constructor(zip(attrs[0::2], attrs[1::2]))
 
+    def startNamespaceDecl(self, prefix, uri):
+        self.namespace_declarations[prefix] = uri
+
     def startElement(self, full_name, attrs):
         name = self._build_name(full_name)
         attrs = self._attrs_to_dict(attrs)
+        if attrs and self.namespace_declarations:
+            attrs["xmlns"] = self.namespace_declarations
+            self.namespace_declarations = OrderedDict()
         self.path.append((name, attrs or None))
         if len(self.path) > self.item_depth:
             self.stack.append((self.item, self.data))
@@ -238,6 +245,7 @@ def parse(xml_input, encoding=None, expat=expat, process_namespaces=False,
     except AttributeError:
         # Jython's expat does not support ordered_attributes
         pass
+    parser.StartNamespaceDeclHandler = handler.startNamespaceDecl
     parser.StartElementHandler = handler.startElement
     parser.EndElementHandler = handler.endElement
     parser.CharacterDataHandler = handler.characters
```

The above code works (for my purposes), but it should probably be made somewhat more elegant if to be included in the official `xmltodict` version.

**Comment by asandvig** [comment]
Some further research/testing shows that `xmlns:*`attributes are supported when `process_namespaces=False` (the default). However, when `process_namesapces=True`, the `xmlns:*` attributes are not included.

This behavior makes it a bit tricky when processing XSD files, as they may include references to declared namespaces inside attribute strings.

Example:
```python
>>> import xmltodict, json
>>> xml = """<?xml version="1.0" encoding="UTF-8"?>
... <xs:schema version="1.0" elementFormDefault="qualified"
...     targetNamespace="http://space.name/"
...     xmlns:xs="http://www.w3.org/2001/XMLSchema">
... 
...     <xs:complexType name="PersonType">
...         <xs:element name="Name" type="xs:string" />
...     </xs:complexType>
... 
... </xs:schema>
... """
>>> print json.dumps(xmltodict.parse(xml), indent=4)
{
    "xs:schema": {
        "@version": "1.0", 
        "@elementFormDefault": "qualified", 
        "@targetNamespace": "http://space.name/", 
        "@xmlns:xs": "http://www.w3.org/2001/XMLSchema", 
        "xs:complexType": {
            "@name": "PersonType", 
            "xs:element": {
                "@name": "Name", 
                "@type": "xs:string"
            }
        }
    }
}
>>> print json.dumps(xmltodict.parse(xml, process_namespaces=True), indent=4)
{
    "http://www.w3.org/2001/XMLSchema:schema": {
        "@version": "1.0", 
        "@elementFormDefault": "qualified", 
        "@targetNamespace": "http://space.name/", 
        "http://www.w3.org/2001/XMLSchema:complexType": {
            "@name": "PersonType", 
            "http://www.w3.org/2001/XMLSchema:element": {
                "@name": "Name", 
                "@type": "xs:string"
            }
        }
    }
}
```

With the second output (`process_namespaces=True`), it is impossible to found out which namespace `"xs:string"`refers to.

**Comment by martinblech** [comment]
Please send a pull request with your proposed changes.
