### ISSUE TITLE
Strip namespaces from attributes?

### ISSUE THREAD

**Issue by gamesbook** [martinblech/xmltodict#113]
I have likely not RTFM properly, but I cannot see how to specify that namespaces get removed from attributes as well.  They appear in the output as:
```
@http:\long\namespace:attribute_name
```

I have written a small routine to strip them out afterwards.

(Very useful library, tho'!)

**Comment by Hellowlol** [comment]
Is xmltodict.parse('xmlstring', process_namespaces=False, attr_prefix='') what you looking for?

**Comment by martinblech** [comment]
Please provide a test case or at least a code example to illustrate the issue.

**Comment by gamesbook** [comment]
I am not sure what you mean by "provide a test case" - I was asking a question on how to do something?

**Comment by martinblech** [comment]
Oh, sorry if I wasn't clear. I meant that it would be easier to troubleshoot if you provides snippet of Python code and an explanation of expected vs actual output. Something in the lines of:

> If I run this:
```python
xmltodict.parse('<a/>')
```
> I get this:
```python
{'a': None}
```
> But I think `xmltodict` should return this instead:
```python
{'a': ''}
```

**Comment by JccSanabria** [comment]
@Hellowlol , your recomendation partially works, but, the attributes still being joined with ns:
