### ISSUE TITLE
Ignoring specific tags

### ISSUE THREAD

**Issue by tanzaho** [martinblech/xmltodict#116]
Is is possible to ignore some specific tags during the parsing ?

Use-case : I have an XML with a field that use sup tags (ex: "Power is:  3<sup>5</sup>") . I need to keep the sup tags in place as raw text;

**Comment by tanzaho** [comment]
Here is how I'm solving it at the moment : 
```
    xmlText = "<a>My random text with math<sup>34</sup> expressions.</a>"
    xmlText = xmlText.replace("<sup>", "&lt;sup&gt;") # replaces sup by an escaped version
    xmlText = xmlText.replace("</sup>", "&lt;/sup&gt;") 
    xmltodict.parse(xmlText)
```

**Comment by martinblech** [comment]
Duplicate of #63
