### ISSUE TITLE
XML formatting

### ISSUE THREAD

**Issue by siv123456** [martinblech/xmltodict#118]
Hi,

i started using xmltodict and i'm very happy with its intuitive usage and outcome.
one thing i didn't find is whether i can format the output xml/ right now i get a one line xml and i would like it to use new lines ,make readable to human eyes.

is there such an option ?

Thanks in advance
Sivan

**Comment by yiufung** [comment]
Use ```pretty=True``` in ```unparse()```. 

```python
>>> mydict={
...     'response': {
...             'status': 'good'
...     }
... }
>>> print xmltodict.unparse(mydict)
<?xml version="1.0" encoding="utf-8"?>
<response><status>good</status></response>
>>> print xmltodict.unparse(mydict, pretty=True)
<?xml version="1.0" encoding="utf-8"?>
<response>
	<status>good</status>
</response>
```

**Comment by siv123456** [comment]
thank you  very much - looks great :)
