### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'force_list'

### ISSUE THREAD

**Issue by mattkohl** [martinblech/xmltodict#123]
I'm thrilled about the new `force_list` feature and trying to use it. However, when I reproduce the test case (Python 3.4 on both Ubuntu 14.04 and Mac OS X) using this input: 
```Python
xml = """
        <servers>
          <server>
            <name>server1</name>
            <os>os1</os>
          </server>
        </servers>
        """
```

and this command: 
```Python
xmltodict.parse(xml, force_list=('server',))
```

I get the following error:
```Python
TypeError: __init__() got an unexpected keyword argument 'force_list'
```

**Comment by scott-vsi** [comment]
Are you installing xmltodict with pip? If so, this feature isn't included in the latest release. 

You can do `pip install git+https://github.com/martinblech/xmltodict.git@master` to install the latest version directly from the repo.

**Comment by mattkohl** [comment]
That fixed it. Thanks!
