### ISSUE TITLE
Is there a way to avoid stripping whitespace?

### ISSUE THREAD

**Issue by chriskessel** [martinblech/xmltodict#126]
I have an (unfortunate) case where leading/trailing whitespace in the XML element is important. It appears that xmltodict is stripping the whitespace though. Is there a way to disable that functionality?

**Comment by martinblech** [comment]
Yes, there is. Just pass `strip_whitespace=False` to `xmltodict.parse`.

**Comment by chriskessel** [comment]
Excellent, thanks!
