### ISSUE TITLE
Force all elements to dict?

### ISSUE THREAD

**Issue by variable** [martinblech/xmltodict#129]
Hi there just wondering if it's possible to force the conversion to dicts even for simple elements,

eg.

```
<root>
   <item>ABC</item>
   <item visible="true">BBB</item>
</root>
```
will give:

`{u'root': {u'item': [u'ABC', {'#text': u'BBB', u'@visible': u'true'}]}}`

can I force the `item` element without attribute to be converted into dict as well? like:

`
{u'root': {u'item': [{'#text': u'ABC'}, {'#text': u'BBB', u'@visible': u'true'}]}}
`
this helps a lot without doing if is dict instance etc.

**Comment by maikhoepfel** [comment]
I agree, it would be nice to see this implemented. I also found a similar need: I'd like to force every value of the dictionary to be a list. E.g. for

```
<root>
   <item>ABC</item>
   <item visible="true">BBB</item>
</root>
```
`xml['root']` will give a list of two items, whereas for 

```
<root>
   <item>ABC</item>
</root>
```
`xml['root']` will return a string. That results in somewhat verbose if-clauses.

**Comment by martinblech** [comment]
Already implemented in #120

**Comment by variable** [comment]
I am sorry but that doesn't seem to be implemented, see:

`>>> b = xmltodict.parse('<root><item attr="abc"></item><item visible="true">BBB</item><item>abc</item></root>', dict_constructor=dict, force_list={'item':'item'})
>>> b
{u'root': {u'item': [{u'@attr': u'abc'}, {'#text': u'BBB', u'@visible': u'true'}, u'abc']}}`

What I want is to make it
>>> b = xmltodict.parse('<root><item attr="abc"></item><item visible="true">BBB</item><item>abc</item></root>', dict_constructor=dict, force_list={'item':'item'})
>>> b
{u'root': {u'item': [{u'@attr': u'abc'}, {'#text': u'BBB', u'@visible': u'true'}, {'#text': u'abc'}]}}

**Comment by variable** [comment]
Nevermind, it's actually implemented by using `force_cdata=True`
