### ISSUE TITLE
xmltodict is not able to parse "%" character

### ISSUE THREAD

**Issue by omps** [martinblech/xmltodict#137]
I am trying to parse a xml file, which on some lines are using "%" in the string, the xmltodict.parse is just failing to trnaslate this. any suggestions.

Sample string
```
<iedit src='${APP_SRC_DIR}/somescript.sh' dst='${APP_DIST}/AppDB/${version}/bin/initAppDBC\
ommon.sh' search='%SEARCH_STRING%' replace='${VARIABLE}'/>
```

Below is the error while i am running the parser.
> Traceback (most recent call last):
>   File "./xmlparser", line 58, in <module>
>     doc = xmltodict.parse(xmlstring)
>   File "$HOME/projects/xmlparser/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
>     parser.Parse(xml_input, True)
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 781, column 143
>

**Comment by martinblech** [comment]
This error is unrelated to `xmltodict`. The XML input is not well formed and this is making Expat fail (as it should).

**Comment by omps** [comment]
thanks figured out the issue was with utf-8 encoding, while rereading the file using.

`with open(filename, "r", encoding='utf-8') as f:`

though with python 2.7, do need to import io module.

```
from io import open
with open(filename, "r", encoding='utf-8') as f:
```

thanks a lot for responding. :+1:
