### ISSUE TITLE
Feature request: better output for plural container/repeating children pattern

### ISSUE THREAD

**Issue by eml-trm** [martinblech/xmltodict#144]
Hi!

It is a common pattern in XML to have a container element in the plural form for repeating element (lists, etc) like this :
```xml
<root>
   <documents>
	<document>
		<texte>word1</texte>
	</document>
	<document>
		<texte>word2</texte>
	</document>
   </documents>
</root>
```

I noticed that then xmltodict output a dictionary with  one child as key. In the end we have  twice the "same" conceptual node. like this  : 

```json
{
    "documents": {
        "document": [
            {
                "texte": "word1"
            },
	    {
		"texte": "word2"
	    }
         ]
    }
}
```
I am aware that there could be two different elements repeated as children of the container but when it is not the case  I would like to have an option to output something like this 

```json
{
     "document": [
         {
              "texte": "word1"
         },
         {
	      "texte": "word2"
	 }
     ]
}
```

This option would produce such an output only when there is only one repeated element name children of the container element.

What is your opinion on this ? would you accept a pull request in that direction (with an option that default to the current behavior of course) ? Would it be easy for you to point us to the part of the code managing repetition (array creation) ?

Thanks a lot for your time.

**Comment by martinblech** [comment]
I don't think xmltodict should go in the direction of interpreting the semantics of XML elements based on their names. This would also break the parse(unparse()) roundtrip feature.
