### ISSUE TITLE
Question concerning stable order of sequence elements when converted to json lists

### ISSUE THREAD

**Issue by timmwagener** [martinblech/xmltodict#145]
Hello @martinblech ,
I have a quick question concerning the order of xml ``sequence`` elements, when converted to ``json``. 
In short: *Is it stable in any way?*
This kind of stability for sequences might be a concern when *diffing* several ``json`` datasets for example with [jsondiff](https://pypi.python.org/pypi/jsondiff)

#### Example data:
----
```xml
<ValueGroup attribute_a="some_value">
      <Value attribute_b="1"/>
      <Value attribute_b="2"/>
      <Value attribute_b="3"/>
</ValueGroup>
```
A guaranteed, stable result in an ideal world would be:
```json
{
    "ValueGroup": {
        "@attribute_a": "some_value", 
        "Value": [
            {
                "@attribute_b": "1"
            }, 
            {
                "@attribute_b": "2"
            }, 
            {
                "@attribute_b": "3"
            }
        ]
    }
}
```
Unstable would be like:
```json
...
{
    "@attribute_b": "2"
},
{
    "@attribute_b": "1"
},
...
```

**Comment by martinblech** [comment]
Hi @timmwagener 
`xmltodict` tries to preserve order whenever possible: adds elements to lists in the order they're received from the parser and uses `OrderedDict` instead of plain `dict` if available. If you do find cases where order isn't preserved, please file them as a bug.
Thanks!
