### ISSUE TITLE
Document must have exactly one root?

### ISSUE THREAD

**Issue by virsystem** [martinblech/xmltodict#149]
What I miss?

>>> type(DEFAULT_CONFIG)
<class 'dict'>
>>> print(DEFAULT_CONFIG)
{'encoding ': 'utf-8', 'header': {'Content-Type': 'type="text/xml"'}}
>>>
>>> print(xmltodict.unparse(DEFAULT_CONFIG))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python35\lib\site-packages\xmltodict.py", line 390, in unparse
    raise ValueError('Document must have exactly one root.')
ValueError: Document must have exactly one root.
>>> print(xmltodict.unparse(DEFAULT_CONFIG),pretty=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python35\lib\site-packages\xmltodict.py", line 390, in unparse
    raise ValueError('Document must have exactly one root.')
ValueError: Document must have exactly one root.

>>> xmltodict.__version__
'0.10.2'

**Comment by dudanogueira** [comment]
You need something like:

DEFAULT_CONFIG = {'oneroot': {'encoding ': 'utf-8', 'header': {'Content-Type': 'type="text/xml"'}}}

**Comment by virsystem** [comment]
Thank you.
I thought he would make default "root".
