### ISSUE TITLE
Please make new release

### ISSUE THREAD

**Issue by peterdemin** [martinblech/xmltodict#151]
Hi, I need `short_empty_elements` in `unparse` badly, could you please make a new release?

**Comment by SnakeNuts** [comment]
As a side-not to this: the pypi file seems to say that it's version '0.10.2' (it's also marked as such in the xmltodict.py file), but the contents (apart from the version no.) seem to be '0.10.1'.

**Comment by martinblech** [comment]
v0.11.0 is out: https://pypi.python.org/pypi/xmltodict/0.11.0
