### ISSUE TITLE
Dont blindly catch TypeError/AttributeError when parsing

### ISSUE THREAD

**Issue by orf** [martinblech/xmltodict#153]
Currently the library uses this code:

```python
    parser.buffer_text = True
    try:
        parser.ParseFile(xml_input)
    except (TypeError, AttributeError):
        parser.Parse(xml_input, True)
```

This is not great if you use callbacks which can raise a TypeError or AttributeError. In this case the original exception is swallowed and another unrelated one is raised (due to the `Parse` call).

Edit: #150 seems to fix this. Please can this be merged?

**Comment by martinblech** [comment]
Merged #150, fixed.
