### ISSUE TITLE
Can XMLtoDict Parse Multiple XML Files into a Single Dictionary?

### ISSUE THREAD

**Issue by mago3421** [martinblech/xmltodict#156]
Hi Martin,

Great library, thanks for creating it. I am using it to read in MAVlink message definitions (from ArduPilot) from an XML file into a single dictionary. However, because of the nature of ArduPilot, there are extra messages defined in other XML files. I've thought about manually combining the XML files but I would like to be able to add files as I go rather than maintain a 'master' file.

Did you have plans to extend support for parsing multiple XML files into a single dictionary? Is this already supported, if so how?

Much thanks! - Marc

**Comment by martinblech** [comment]
There's no need to change xmltodict to support this use case. You could do something like this:

```python
superdict = {}
for filepath in filepaths:
  superdict[filepath] = xmltodict.parse(open(filepath))
```
