### ISSUE TITLE
Custom XML entities are coming out as None, as of 0.11

### ISSUE THREAD

**Issue by rspeer** [martinblech/xmltodict#159]
I use xmltodict to parse a rather complex XML file, the "JMdict" Japanese dictionary. The file defines a large number of custom entities, as shorthand for categories such as parts of speech.

I was previously using xmltodict 0.10.2 to parse the file, and it worked correctly. But now, the entities are coming out with values of None.

To reproduce:

- Download JMdict from http://ftp.monash.edu.au/pub/nihongo/JMdict.gz
- Extract the file and rename its extracted content to "JMdict.xml"
- Run this Python code (I'm running it in an IPython 5.1 shell on Python 3.5.3):

```python
>>> import xmltodict
>>> data = open('JMdict.xml').read()
>>> xml = xmltodict.parse(data)
>>> entry = xml['JMdict']['entry'][0]
>>> entry

OrderedDict([('ent_seq', '1000000'),
             ('r_ele',
              [OrderedDict([('reb', 'ヽ')]), OrderedDict([('reb', 'くりかえし')])]),
             ('sense',
              OrderedDict([('pos', None),
                           ('gloss',
                            [OrderedDict([('@xml:lang', 'eng'),
                                          ('#text',
                                           'repetition mark in katakana')]),
                             OrderedDict([('@xml:lang', 'ita'),
                                          ('#text',
                                           'simbolo di ripetizione in katakana')])])]))])
```

The entry being parsed looks like this:

```xml
<entry>
<ent_seq>1000000</ent_seq>
<r_ele>
<reb>ヽ</reb>
</r_ele>
<r_ele>
<reb>くりかえし</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>repetition mark in katakana</gloss>
<gloss xml:lang="ger">(n) Wiederholung</gloss>
<gloss xml:lang="ger">Refrain</gloss>
</sense>
</entry>
```

Note that the value `&n;` came out as `None`. It used to come out as the string "noun (common) (futsuumeishi)", because line 306 contains:

```xml
<!ENTITY n "noun (common) (futsuumeishi)">
```

I'm working around this for now by downgrading to 0.10.2.

**Comment by martinblech** [comment]
The latest version of xmltodict disables XML entities by default for security reasons (see 86c3ed6f0e6ea8bb07f98a3f0730e88c34828c84). Just pass `disable_entities=False` if you need this.

**Comment by rspeer** [comment]
Thanks for the response. I think you should add this compatibility-breaking change to the Changelog, though.

**Comment by martinblech** [comment]
Sure, my bad! Happy to merge if you send a PR with the change you'd like to see in the Changelog.
