### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by uludag** [martinblech/xmltodict#162]
Link (https://admin.fedoraproject.org/pkgdb/acls/name/python-xmltodict) given for "official Fedora package for xmltodict" looks broken.

--mahmut

**Comment by Pertempto** [comment]
Is [this](https://apps.fedoraproject.org/packages/python-xmltodict) the correct page? If it is I'll fix it.

**Comment by uludag** [comment]
Above link looks correct.
