### ISSUE TITLE
Attributes in streaming mode

### ISSUE THREAD

**Issue by Dafvid** [martinblech/xmltodict#172]
I was trying to get the attributes of the items at the specified level. I found that changing the matching condition in startElement fixed the issue.
Instead of
`if len(self.path) > self.item_depth:`
it's
`if len(self.path) >= self.item_depth:`

Then the attributes gets added to `self.item` and passed to the callback. Otherwise only the child items get attributes added. Is it possible to add this change?
https://github.com/martinblech/xmltodict/blame/master/xmltodict.py#L105

**Comment by martinblech** [comment]
Please send a pull request with all test cases updated if you want this line changed. Thanks!
