### ISSUE TITLE
xmltodict mysteriously broke

### ISSUE THREAD

**Issue by siggib007** [martinblech/xmltodict#175]
What was working 30 min ago is no longer working. Now I'm getting this error in all my scripts
  File "\python\QualysHostDetection.py", line 161, in MakeAPICall
    dictResponse = xmltodict.parse(WebRequest.text)
  File "C:\Users\sbjarna\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
Exact same script and same XML that worked 30 min ago is now failing

**Comment by siggib007** [comment]
So what does closed without any comments mean?

**Comment by siggib007** [comment]
My apologies for asking a stupid obvious question :-(

**Comment by martinblech** [comment]
There isn't enough information in this report to reproduce the issue. Could you come up with a specific example of XML that produces this error?

**Comment by siggib007** [comment]
Don't worry about it, like I said it was a stupid question. Solved it after doing some research. On a side note if you had told me right off that my question was lacking rather just closing this, that would have saved me some grief. But it's all good now.
