### ISSUE TITLE
unparse nested attributes

### ISSUE THREAD

**Issue by mpf82** [martinblech/xmltodict#176]
What I have:
```
{'item': [{'@n': 'LEVEL_1',
           '@v': {'item': [{'@n': 'KEY_2', '@v': 'VAL_2', '@x': 0},
                           {'@n': 'KEY_3', '@v': 'VAL_3', '@x': 0},
                           {'@n': 'KEY_1', '@v': 'VAL_1', '@x': 0}]},
           '@x': 1}]}
```

What I want:
```
<item
    n="LEVEL_1"
    x=1
    v="
        <item n="KEY_1" v="VAL_1" x=0 />
        <item n="KEY_2" v="VAL_2" x=0 />
        <item n="KEY_3" v="VAL_3" x=0 />
    "
/>
```
Of course the content of ``v=""`` needs to be escaped. It does not need line breaks, they are just here for readability and I do not care about the order of the items.

What ``xmltodict.unparse(xd, full_document=False)`` returns:

``<item x="1" v="{'item': [{'@x': 0, '@v': 'VAL_3', '@n': 'KEY_3'}, {'@x': 0, '@v': 'VAL_2', '@n': 'KEY_2'}, {'@x': 0, '@v': 'VAL_1', '@n': 'KEY_1'}]}" n="LEVEL_1"></item>``

I tried to write my own preprocessor, but could not get any useful output.

The idea is to have deep nested structures within the attributes, that can be parsed as XML later.

Changing the structure of the original input is also an option.

**Comment by martinblech** [comment]
Thanks for the input!

Attribute values in XML are strings. xmltodict won't look inside these values, it will just use them as is.

You should preprocess your nested dicts into strings beforehand if you want to get this output for this very specific use case. I won't implement this into xmltodict, you'd have to deal with this preprocessing step externally.

**Comment by javadev** [comment]
```json
{"item": [{"n": "LEVEL_1",
           "v": {"item": [{"n": "KEY_2", "v": "VAL_2", "x": 0},
                           {"n": "KEY_3", "v": "VAL_3", "x": 0},
                           {"n": "KEY_1", "v": "VAL_1", "x": 0}]},
           "x": 1}]}
```

may be converted to xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<item array="true">
  <n>LEVEL_1</n>
  <v>
    <item>
      <n>KEY_2</n>
      <v>VAL_2</v>
      <x number="true">0</x>
    </item>
    <item>
      <n>KEY_3</n>
      <v>VAL_3</v>
      <x number="true">0</x>
    </item>
    <item>
      <n>KEY_1</n>
      <v>VAL_1</v>
      <x number="true">0</x>
    </item>
  </v>
  <x number="true">1</x>
</item>
```
