### ISSUE TITLE
No way to change indentation to spaces

### ISSUE THREAD

**Issue by guysoft** [martinblech/xmltodict#177]
Hey,
Trying to read and write Jenkins jobs, but I can't preform a round trip without the indentation changing.
Jenkins uses 2 spaces and xmltodict.unparse only supports unparsing using tabs.

Example:

```
import xmltodict
a = """<?xml version='1.0' encoding='UTF-8'?>
<project>
  <actions/>
</project>
"""

print(xmltodict.unparse(xmltodict.parse(a), None, 'UTF-8', True, True, pretty=True))
```

Output is with tabs and not spaces

**Comment by DanielGibbsNZ** [comment]
The [documentation for `unparse`](https://github.com/martinblech/xmltodict/blob/master/xmltodict.py#L426) says:

> The `pretty` parameter (default=`False`) enables pretty-printing. In this mode, lines are terminated with `'\n'` and indented with `'\t'`, but this can be customized with the `newl` and `indent` parameters.

**Comment by guysoft** [comment]
Ok, thanks, been a while since I did this so I need to figure out what I was doing.

For completeness, here is the code example above that does what I asked for:
I checked and it does do what I wanted at the time, so I am closing this issue.
```
import xmltodict
a = """<?xml version='1.0' encoding='UTF-8'?>
<project>
  <actions/>
</project>
"""

print(xmltodict.unparse(xmltodict.parse(a), None, 'UTF-8', True, True, pretty=True,newl="\n",indent="  "))
```
