### ISSUE TITLE
json to xml with "self-closing tags"

### ISSUE THREAD

**Issue by Kamakshilk** [martinblech/xmltodict#184]
Hi experts, 
 Is there a way to convert from json to xml with self-closing tags.
Example: My json is define as below 
arr = [{"@name": "transactionId", "@value" : "1234", "@type": "u32"},
       {"@name": "numTransactions", "@value" : "1", "@type":"u32"}]

with xmltodict.unparse(), the generated XML has these lines.
<arr name="transactionId" value="1234" type="u32"></arr>
<arr name="numTransactions" value="1" type="u32"></arr>

But I need the self-closing tags, like this
<arr name="transactionId" value="1234" type="u32"/>
<arr name="numTransactions" value="1" type="u32"/>

Looking forward for experts suggestions

regards

**Comment by vstoykov** [comment]
@Kamakshilk you should use markdown to insert code. Currently your Python code is not well formatted and the xml is missing.

**Comment by Kamakshilk** [comment]
Thank you @vstoykov. Im sorry about my ignorance. 
I wanted to understand while converting json to xml is there is a way of generating self-closing tags mentioned in case 2 rather than the format in case 1 below.
``` python
<root>
	<arr name="transactionId" value="1234" type="u32"></arr>
	<arr name="numTransactions" value="1" type="u32"></arr>
</root>
```
``` python
<root>
	<arr name="transactionId" value="1234" type="u32"/>
	<arr name="numTransactions" value="1" type="u32"/>
</root>
```

**Comment by Kamakshilk** [comment]
Brilliant !! this work.  Thank you so much @matheboy and @vstoykov 
```python
xmltodict.unparse(js1,short_empty_elements=True,pretty=True)

**Comment by vstoykov** [comment]
@Kamakshilk I think that because your issue is resolved you can close it now.

**Comment by Kamakshilk** [comment]
Thank you

**Comment by javadev** [comment]
```xml
<root>
	<arr name="transactionId" value="1234" type="u32"/>
	<arr name="numTransactions" value="1" type="u32"/>
</root>
```
may be converted to json:
```json
{
  "root": {
    "arr": [
      {
        "-name": "transactionId",
        "-value": "1234",
        "-type": "u32",
        "-self-closing": "true"
      },
      {
        "-name": "numTransactions",
        "-value": "1",
        "-type": "u32",
        "-self-closing": "true"
      }
    ]
  },
  "#omit-xml-declaration": "yes"
}
```
