### ISSUE TITLE
TypeError: string indices must be integers when parsing a CAMT.053 file

### ISSUE THREAD

**Issue by lasalesi** [martinblech/xmltodict#188]
Hi all,

I observed the following error:
* XML: http://www.sepa-tool.de/files/Camt.053.xml

Code:

    import xmltodict
    doc = xmltodict.parse(content)
    iban = doc['Document']['BkToCstmrStmt']['Stmt']['Acct']['Id']['IBAN']
    for entry in doc['Document']['BkToCstmrStmt']['Stmt']['Ntry']:
        date = entry['BookgDt']['Dt']
        for transaction in entry['NtryDtls']['TxDtls']:
            unique_reference = transaction['Refs']['AcctSvcrRef']

This fails with the following traceback:

    Traceback (most recent call last):
      File "/home/user/camt.py", line 464, in read_camt053
        unique_reference = transaction['Refs']['AcctSvcrRef']
    TypeError: string indices must be integers

In some cases, several records are read fine before the error occurs. Looking at the underlying json seems to be all fine.

Is this a bug or is something else wrong? Python is v2.7

**Comment by matthiasnehls** [comment]
the problem is that if only on record is in your transactions it`s not a list so the error appear. if there are more transactions everything works fine.

i have the same problem and try tommorow write a solution

**Comment by amritha-narayanan** [comment]
Is it planned to fix this bug? :)

**Comment by matthiasnehls** [comment]
in the python script itself there is allready the solution:😁

You can use the force_list argument to force lists to be created even
    when there is only a single child of a given level of hierarchy. The
    force_list argument is a tuple of keys. If the key for a given level
    of hierarchy is in the force_list argument, that level of hierarchy
    will have a list as a child (even if there is only one sub-element).
    The index_keys operation takes precendence over this. This is applied
    after any user-supplied postprocessor has already run.

**Comment by amritha-narayanan** [comment]
Thanks a lot. It works now

**Comment by javadev** [comment]
@amritha-narayanan issue may be closed then.
