### ISSUE TITLE
XML elements with spaces only

### ISSUE THREAD

**Issue by flengyel** [martinblech/xmltodict#196]
Is it possible for xmldict to preserve verbatim XML elements that contain only spaces between the element's start and ending  tag? For example, instead of compressing  &lt;ABC&gt;    &lt;/ABC&gt; to  &lt;ABC&gt; &lt;/ABC&gt;, is it possible to not strip out the spaces so the unparsed XML retains the spaces in   &lt;ABC&gt;    &lt;/ABC&gt;?

**Comment by flengyel** [comment]
After reading the code I see that it's only necessary to add the argument strip_whitespace=False to parse(), as in  xmldict.parse(data, strip_whitespace=False). [The reason for my query comes from an Oracle peculiarity that treats certain blanks as NULL...]

**Comment by javadev** [comment]
```xml
<ABC> </ABC>
```

may be converted to json:

```json
{
  "ABC": " ",
  "#omit-xml-declaration": "yes"
} 
```
