### ISSUE TITLE
Error in parsing list with only one entry

### ISSUE THREAD

**Issue by Brun059** [martinblech/xmltodict#201]
A list with two or more entries translate correctly into a list <list>
The same list, list with only one entry does not yield a list with one entry as expected,
instead it just returns <class 'collections.OrderedDict'>

in either case, using doc = xmltodict.parse(payload, encoding='utf-8')

[Error in parsing arrays with only one entry.pdf](https://github.com/martinblech/xmltodict/files/2736326/Error.in.parsing.arrays.with.only.one.entry.pdf)

**Comment by fabiosussetto** [comment]
I've seen the same behaviour and I think it's quite inconsistent and error-prone.

**Comment by martinblech** [comment]
Thanks for pointing out the `force_list` option @fabiosussetto. Please take a look at #14 for a longer discussion of this issue.
