### ISSUE TITLE
Parker convention is not implemented correctly

### ISSUE THREAD

**Issue by AndreiPashkin** [martinblech/xmltodict#207]
It seems like the way of how the library converts XML using Parker convention differs from how it's defined originally in this repository:
https://github.com/doekman/xml2json-xslt

Here is the comparison:

**Input data**
```xml
<root>
    <person>
        <age>12</age>
        <height>1.73</height>
    </person>
    <person>
        <age>12</age>
        <height>1.73</height>
    </person>
</root>
```

**Using xmltodict**

Output:
```json
{
    "person": [
        {
            "age": 12,
            "height": 1.73
        },
        {
            "age": 12,
            "height": 1.73
        }
    ]
}
```

**Using [XSLT document](https://github.com/doekman/xml2json-xslt/blob/master/xml2json.xslt) from the original Google repository**

Output:
```json
{
    "root":[
        {
            "age":12,
            "height":1.73
        },
        {
            "age":12,
            "height":1.73
        }
    ]
}
```

**Comment by martinblech** [comment]
I wasn't aware that the Parker convention existed. It was never my intent to follow it.

**Comment by AndreiPashkin** [comment]
Then it probably shouldn't be called "Parker convention" in the library.

**Comment by mpf82** [comment]
> Then it probably shouldn't be called "Parker convention" in the library.

What are you referring to? 

https://github.com/martinblech/xmltodict/search?q=Parker&unscoped_q=Parker

>  We couldn’t find any code matching 'Parker' in martinblech/xmltodict

**Comment by AndreiPashkin** [comment]
It is my mistake, I created the issue in wrong project
