### ISSUE TITLE
Can you do a new release?

### ISSUE THREAD

**Issue by stevesimmons** [martinblech/xmltodict#228]
Hi Martin,

Can you please do a 0.13.0 release? 

I would like a pip-installable version that uses the new strip_namespaces option in #224 . 

It would also be great if that release could fix #166 too. 
Is that as simple as changing this:
```
            if self._should_force_list(key, data):
                item[key] = [data]
```
to this?
```
            if self._should_force_list(key, data):
                item[key] = [] if data is None else [data]
```

**Comment by lelroy** [comment]
Yes, this has plagued me also.  I have had to convert empty items to empty lists also.  Argh.

**Comment by skewty** [comment]
# 253

**Comment by skewty** [comment]
#253

**Comment by martinblech** [comment]
Just uploaded https://pypi.org/project/xmltodict/0.13.0/, sorry for the delay!
