### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by Seljelid** [martinblech/xmltodict#237]
I saw that there hasn't been any releases for approx. 12 months. Will there be a new release soon?

**Comment by skewty** [comment]
#253

**Comment by javadev** [comment]
We have a [java library](https://github.com/javadev/underscore-java). 100% code coverage, monthly releases. Quick response.

**Comment by martinblech** [comment]
Just uploaded https://pypi.org/project/xmltodict/0.13.0/, sorry for the delay!
