### ISSUE TITLE
Use dict instead of OrderedDict for python 3.6

### ISSUE THREAD

**Issue by aymanhs** [martinblech/xmltodict#252]
For Python >= 3.6, dictionary are Sorted by insertion order, so avoid the use of OrderedDict for those python versions.

**Comment by epatters** [comment]
The main function `parse` has `dict_constructor` keyword argument useful for this purpose.

**Comment by danielloader** [comment]
Is this available in the pypi package or the source package only?

**Comment by ehn-pkalinowski** [comment]
it is in pypi

**Comment by TomDufall** [comment]
This is a CPython implementation detail for Python 3.6, although I think it's part of the dict spec from 3.7 onwards?

**Comment by soustruh** [comment]
Ordered dictionaries are just like regular dictionaries but have some extra capabilities relating to ordering operations. They have become less important **now that the built-in dict class gained the ability to remember insertion order (this new behavior became guaranteed in Python 3.7)**.

https://docs.python.org/3.7/library/collections.html?highlight=ordereddict#ordereddict-objects

**Comment by endlisnis** [comment]
And since Python3.6 is now end-of-life (https://pythonspeed.com/articles/stop-using-python-3.6), this project should just blindly use "dict" instead of "OrderedDict".

**Comment by manngo** [comment]
> The main function `parse` has a `dict_constructor` keyword argument useful for this purpose.

Is that documented? How would I use that?

**Comment by gotofritz** [comment]
@manngo you can see an example here https://github.com/martinblech/xmltodict/blob/ae19c452ca000bf243bfc16274c060bf3bf7cf51/tests/test_xmltodict.py#L350

**Comment by manngo** [comment]
@gotofritz Thanks, that worked. It makes the result much easier to work with.

> @manngo you can see an example here
> 
> https://github.com/martinblech/xmltodict/blob/ae19c452ca000bf243bfc16274c060bf3bf7cf51/tests/test_xmltodict.py#L350
