### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nathanalderson** [martinblech/xmltodict#253]
It's been over a year since the last release and there have been a number of improvements in that time. Any chance we could see a new release soon?

**Comment by skewty** [comment]
Perhaps some of you could get by with a `git+` line in your `requirements.txt`.

Manual PIP install using:

```shell
pip install git+https://github.com/martinblech/xmltodict.git@ae19c452ca000bf243bfc16274c060bf3bf7cf51#egg=xmltodict
```
Replace hash above with any commit you need.  Note the version number will still show: `0.12.0`.

**Comment by HarrySky** [comment]
@martinblech awesome library, can you please publish a new release to PyPI? Is this library not maintained anymore or do you need help (maintainers/reviewers)?

**Comment by hsansilva** [comment]
> @martinblech awesome library, can you please publish a new release to PyPI? Is this library not maintained anymore or do you need help (maintainers/reviewers)?

Glad to help if this is needed.

**Comment by haferburg** [comment]
> 
> 
> Perhaps some of you could get by with a `git+` line in your `requirements.txt`.
> 
> Manual PIP install using:
> 
> ```shell
> pip install git+https://github.com/martinblech/xmltodict.git@ae19c452ca000bf243bfc16274c060bf3bf7cf51#egg=xmltodict
> ```
> 
> Replace hash above with any commit you need. Note the version number will still show: `0.12.0`.

`pip install git+https://github.com/martinblech/xmltodict.git#egg=xmltodict` worked as well.

**Comment by martinblech** [comment]
Just uploaded https://pypi.org/project/xmltodict/0.13.0/, sorry for the delay!
