### ISSUE TITLE
ExpatError: reference to invalid character number of a datetime value

### ISSUE THREAD

**Issue by lbhtran** [martinblech/xmltodict#254]
Hi, I'm using xmltodict to parse a response from an API call. I got the ExpatError issue for a datetime value. I have checked the data and this value from raw xml string multiple times and there is no special characters. There are datetime data in the string which have been parsed without any issue including datetime value from the same tag as the one causing problem. Is there anyway I can resolve or ignore this error?

(sorry, I can't paste code to github from my workspace)

**Comment by loscil06** [comment]
Could you mockup some arbitrary data? The structure is what counts and the format of the date.

**Comment by lbhtran** [comment]
Hi, I found the error. It was a special character that couldn’t be read. The code works fine after this character is removed.
