### ISSUE TITLE
bash: line 1:  1374 Killed

### ISSUE THREAD

**Issue by lerchikva** [martinblech/xmltodict#259]
Hello.
Please help XML to JSON.
I am low on RAM so the server is killing the process.

`python -c 'import xmltodict, sys, json; json.dump(xmltodict.parse(sys.stdin.read(), process_namespaces=True), sys.stdout, indent=4);' < ./public/my.xml > ./public/my.json`

```
bash: line 1:  1374 Killed                  python -c 'import xmltodict, sys, json; json.dump(xmltodict.parse(sys.stdin.read(), process_namespaces=True), sys.stdout, indent=4);' < ./public/my.xml > ./public/my.json
```

**Comment by okyanusoz** [comment]
Hello,
It seems like you're working with a large file. Consider using [Streaming Mode](https://github.com/martinblech/xmltodict#streaming-mode).

**Comment by hartwork** [comment]
My vote for closing as "not a bug in xmltodict".
