### ISSUE TITLE
Unparsing returns a ValueError ('The document must have exactly one root') while using open() fn.

### ISSUE THREAD

**Issue by vvekraman** [martinblech/xmltodict#261]
**The objective is to convert JSON to XML**
The code reads the JSON.txt, converts it into XML and writes it on to JSON_to_xml.txt. The below code returns a value error while unparsing giving an error that the file has multiple roots even though it has a single root.
```
import xmltodict
import json
import sys

sys.stdout = open('JSON_to_XML.txt', 'w')
print(json.dumps(xmltodict.unparse(open("JSON.txt", "r").read()))) 
sys.stdout.close()
```

The content of the JSON.txt is as follows,
```{"note": {"to": "Tove", "from": "Jani", "heading": "Reminder", "body": "Dont forget me this weekend!"}}```

If I just copy the contents of the file to the script as shown below, it gives the output in proper XML format.
```
import xmltodict
import json
                                                                
print(json.dumps(xmltodict.unparse(
    {"note": {"to": "Tove", "from": "Jani", "heading": "Reminder", "body": "Dont forget me this weekend!"}})))
```
Your comments and suggestions are highly appreciated. Thank you.

**Comment by mpf82** [comment]
In case 2 you are passing a dict to the function, which is the way to go: ``xmltodict.unparse({"note":...`` 

In case 1, the one raising the ValueError, you are passing a JSON string (the result of ``read()``) to the function. You need to convert the result of ``read()`` to a dict first.

**Comment by vvekraman** [comment]
Hello Mike, 
Thanks a lot for the information. Got it resolved.

```import xmltodict
import json
import sys

JSON to XML

f = open("JSON.txt")

sys.stdout = open('JSON_to_XML.txt', 'w')
print(json.dumps(xmltodict.unparse(json.load(f))))
sys.stdout.close()
