### ISSUE TITLE
not well-formed (invalid token) error when parsing valid xml

### ISSUE THREAD

**Issue by abowcut** [martinblech/xmltodict#268]
When parsing the below xml string I am receiving a "not well-formed (invalid token): line 4, column 217" error, but it seems to me the character at column 217 on line 4 is a typical period character (U+002E) and I've used a wide range of xml validators that have all classified this xml as a valid document.

Would expect that I would be able to parse this valid xml document.

I'm simply running

`t = xmltodict.parse(xml)`

where _xml_ is the utf-8 string attached:

[t.txt](https://github.com/martinblech/xmltodict/files/6130677/t.txt)

**Comment by pythonist552** [comment]
> When parsing the below xml string I am receiving a "not well-formed (invalid token): line 4, column 217" error, but it seems to me the character at column 217 on line 4 is a typical period character (U+002E) and I've used a wide range of xml validators that have all classified this xml as a valid document.
> 
> Would expect that I would be able to parse this valid xml document.
> 
> I'm simply running
> 
> `t = xmltodict.parse(xml)`
> 
> where _xml_ is the utf-8 string attached:
> 
> [t.txt](https://github.com/martinblech/xmltodict/files/6130677/t.txt)

I could not preproduce with Python 3.8.3 for Windows (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]:
```
import sys
import xmltodict

print(sys.version)

with open("t.txt", "rt") as inFile:
    buffer = inFile.read()
    result = xmltodict.parse(buffer)

for item in result:
    for subitem in result[item]:
        print("%s=%s" % (subitem, result[item][subitem]))

```` 
Result:
```` 
3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
JobTitle=Real Estate Transaction Coordinator
Company=Welch Team
JobDescription=The mission of Welch Team is through our expertise in real estate, Welch Team is committed to helping our neighbors and each other reach personal and professional goals as a community.Who are we looking for?A Licensed Real Estate Transaction Coordinator who is outgoing, draws energy from working with people, and is optimistic. Someone who thrives in a multi-tasking evironment of helping others and overcoming challenges. They have a strong sense of urgency, but not at the expense of quality. In addition, he/she demonstrates on a daily basis the knowledge, attitudes, skills, and habits of a high achiever who is committed to putting customers first, doing the right thing, seeking win-win agreements, handles a variety of issues that may arise with a cool temperament and is highly organized. The Transaction Coordinator must be adaptable to change and be solutions oriented. He/She will manage the entire contract-to-close process efficiently and effectively to ensure all transactions close on time, with little or no hassle to clients and third parties. This individual must provide exceptional customer service.Essential duties and responsibilitiesCreate a smooth closing from start to finish.Act as liaison between real estate agents, customers, attorneys, escrow companies, and mortgage brokers Maintain active Florida real estate licenseEnsure all timelines are met or extended as neededMaintain accurate and compliant filesUse Google Drive &amp; Property BaseBe the first point of contact/resource for agents (and customer, attorneys, lenders, appraisers, other transaction coordinators/Realtors, etc.)Stay in good communication with the agent if any issues arise that they need to handle or negotiateKeep everyone up to date with information needed to finalize the closing processDraft closing disbursement authorizations for our listings and our buyer side transactions prior to closingFollow up with clients after the sale to check in and request a testimonial/referralMust have a Florida real estate license.
JobLocation=Evansville, IN USA
JobLocationRegion=IN
JobLocationCity=Evansville
JobLocationPostalCode=47708
JobLocationLatitude=37.996246
JobLocationLongitude=-87.57019
PostedDate=2021-03-11T21:22:26+00:00
JobLocationCountry=USA
JobPostingURL=https://introview.com/posts/evansville_in_usawelch_teamreal_estate_transaction_coordinator/vM9LdWYz8A
```` 

Current version of xmltodict: **pip show xmltodict**
```` 
Name: xmltodict
Version: 0.12.0
Summary: Makes working with XML feel like you are working with JSON
Home-page: https://github.com/martinblech/xmltodict
Author: Martin Blech
Author-email: martinblech@gmail.com
License: MIT
Location: c:\python38\lib\site-packages
Requires: 
Required-by: n0struct
```` 

All files in one archive: [xmltodict_CDATA.zip](https://github.com/martinblech/xmltodict/files/6134769/xmltodict_CDATA.zip)

**Comment by abowcut** [comment]
Thanks for your help, it turns out the issue was the "^A" character or \x01 in that description.
Typically I was passing bytes to xmltodict.parse() not a string, so if the bytes are decoded and the \x01 removed (like in the file I attached and you used) then it will parse correctly.

I am a little surprised that the "^A" or \x01 char triggers the "not well-formed" error as it seems it shouldn't but is easy enough to account for.
