### ISSUE TITLE
List type object with single parameter is being converted into wrong format

### ISSUE THREAD

**Issue by mdakilansari** [martinblech/xmltodict#271]
**Format is wrong after  conversion of List object with single value.** 

example:

 _{
 "name": "ParameterName",
  "p": "10638"
}_

Expected:

 **_{
 "name": "ParameterName",
  "p": ["10638"]
}_**

Please look into this issue.
Attaching Sample XML snip for reference.
![image](https://user-images.githubusercontent.com/25582328/118889082-32f2e700-b91a-11eb-8a5c-583563888de8.png)

Thank you in advance.

**Comment by deridiot** [comment]
as i stumbled over this as well let me point you and other people looking for this to the correct place:

https://github.com/martinblech/xmltodict/blob/master/xmltodict.py#L266

set the force_list parameter on the parse method to either True to always return lists for all elements or provide a tuple with the tag names you do want as lists. works like a charm... just very much undocumented unless we consider the code documenting itself ;)
