### ISSUE TITLE
What does full document do? Assistance removing <?xml version="1.0" encoding="utf-8"?> from unparse

### ISSUE THREAD

**Issue by DOH-Manada** [martinblech/xmltodict#276]
Using `xmldict.unparse` with default parameters inserts a meta-string at the start.

Is there anyway to remove this? I noticed setting `full_document=False` would remove it, but I'm not sure what it does.

**Comment by martinblech** [comment]
https://stackoverflow.com/questions/13743250/meaning-of-xml-version-1-0-encoding-utf-8
