### ISSUE TITLE
Escape `&` character while unparsing

### ISSUE THREAD

**Issue by aashutoshbane** [martinblech/xmltodict#277]
Hi,

I am trying to unparse the below xml:

`<docLink>
        <docLinkId>11763263</docLinkId>
	<webUrl>https://some.domain.com?a=10&b=20</webUrl>
</docLink>`

getting this error:
`xml.parsers.expat.ExpatError: not well-formed (invalid token)`

If I remove the **`&`** it works fine.

Is there any solution for the above issue or any workaround?

**Comment by javadev** [comment]
```xml
<docLink> <docLinkId>11763263</docLinkId> <webUrl>https://some.domain.com?a=10&b=20</webUrl> </docLink>
```
is not valid

it should be
```xml
<docLink> <docLinkId>11763263</docLinkId> <webUrl>https://some.domain.com?a=10&amp;b=20</webUrl> </docLink>
```
