### ISSUE TITLE
`xml_attribs` argument ignored when streaming.

### ISSUE THREAD

**Issue by elibixby** [martinblech/xmltodict#278]
My expected behavior would be for either (1) the `xml_attribs` argument to raise an error or warning if used with the `item_callback` argument, or (2) the attributes to be included in the returned dictionary inside the callback, without needing to reconstruct it myself from the path argument. 

Instead it silently leaves them out.

**Comment by timng** [comment]
Hi, check this PR https://github.com/martinblech/xmltodict/pull/238

**Comment by martinblech** [comment]
Fixed by #238, thanks @timng!
