### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by zidingz** [martinblech/xmltodict#279]
Hey there!

I belong to an open source security research community, and a member (@yetingli) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by cena7** [comment]
what is the resolution on this ? is there anything to be alarmed before using this  ?

**Comment by JamieSlome** [comment]
We are still waiting for a response from the maintainer regarding the issue.

The report can be found here:
https://huntr.dev/bounties/b32adea9-bb33-45a5-a1ad-c504e73e907f/

It is currently private and only accessible to @martinblech 👍

**Comment by kdeldycke** [comment]
#321 has been closed so I guess this issue can be also closed.
