### ISSUE TITLE
Only OrderedDicts are returned

### ISSUE THREAD

**Issue by pjakobsen** [martinblech/xmltodict#28]
This may just be a documentation issue, but when I run:  (Python 2.7 OS X)

```
foo = xmltodict.parse("""<?xml version="1.0" ?>
        <person>
          <name>john</name>
          <age>20</age>
        </person>""")

    print foo
```

I get:

Output:  OrderedDict([(u'person', OrderedDict([(u'name', u'john'), (u'age', u'20')]))])

In a nested XML document, this is making hard for me to turn this into JSON

**Comment by scharfmn** [comment]
Thank you for a very fine library. It would be very nice to have the option to just go straight to dict. As noted [here](http://stackoverflow.com/a/25055461/1599229): "creating a large dictionary (with 100-10000 keys) is around 7-8x faster than creating an OrderedDict with same keys. (Verified using %timeit in ipython)." The OrderedDict overhead is not what's really advertised by the library's name.

**Comment by vstoykov** [comment]
Yes in situations where speed is important and order of items not, then ability to use native dict instead of OrderedDict will be a good option.

**Comment by vstoykov** [comment]
@scharfmn I just found that you can use:

    foo = xmltodict.parse(xml_string, dict_constructor=dict)

**Comment by kmonsoor** [comment]
@vstoykov good find, mate. (y)

**Comment by Inveracity** [comment]
@vstoykov :+1:

**Comment by alexcombessie** [comment]
Awesome @vstoykov very good solution

**Comment by vstoykov** [comment]
In future if Python 3.7+ is detected then instead of `collections.OrderedDict` the normal `dict` can be used by default because it will preserve the order by default.

**Comment by yiga2** [comment]
@vstoykov just wanted to note that `OrderedDict` is still the default constructor when using Python 3.7.1.

**Comment by yiga2** [comment]
@martinblech a year later, would you ever implement [this ](https://github.com/martinblech/xmltodict/issues/28#issuecomment-407353343) ?
Not a big deal to always add `dict_constructor=dict` but could be missed and be avoided.
