### ISSUE TITLE
how to keep &gt;

### ISSUE THREAD

**Issue by wangke1970** [martinblech/xmltodict#288]
how to keep &gt;
>>> xml = '''<password>L_w-9BDTXP& gt;5!,BGXs6L$</password>'''
>>> d = xmltodict.parse(xml)
>>> print(d)
OrderedDict([('password', 'L_w-9BDTXP>5!,BGXs6L$')])

& gt;  change to  >

                                                         thanks

**Comment by javadev** [comment]
You may use cdata blocks.
