### ISSUE TITLE
Error when parsing an XML with null byte

### ISSUE THREAD

**Issue by orbart** [martinblech/xmltodict#291]
When trying to parse an XML which has a null byte, such as:
`<test>string\x00</test>`
We get an error:
`>>> parse("<test>string\x00</test>")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orp/dev/medigator/env/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 12`

**Comment by javadev** [comment]
It may be converted to this json

```json
{
  "test": "string\\x00",
  "#omit-xml-declaration": "yes"
}
```

**Comment by orbart** [comment]
Yes, but what if that's the json I get from an external service? (which was the case here, I just simplified the json so it's easy to test and doesn't contain private information)

**Comment by hartwork** [comment]
A null byte violates the XML spec. My vote for closing as "works as as it should".
