### ISSUE TITLE
Add Python 3.9 and make a new release on PyPI

### ISSUE THREAD

**Issue by veghp** [martinblech/xmltodict#293]
Thanks for this package. Please add Python 3.9 to https://github.com/martinblech/xmltodict/blob/master/setup.py ; and make a new release on PyPI so that dependencies (https://github.com/Edinburgh-Genome-Foundry/SnapGeneReader) can be installed (latest release was on Feb 11, 2019). 

The tests pass on Python 3.9.

**Comment by martinblech** [comment]
Just added 3.9 support and pushed a new version to PyPI.
