### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by Simonvj93** [martinblech/xmltodict#320]
God day,

Are there any plans to support new python versions?

Kind regards,
Simon

**Comment by alucarddelta** [comment]
I'm currently using it on 3.11.2 with out any issues... What are you seeing that is that is broken?

**Comment by Simonvj93** [comment]
I dont remember the response I got, and I just downgraded Pyhton. 
Thank you for taking the time to answer me, I appreciate it. 
Will reopen the issue in the future with the error response if it happens again.
