### ISSUE TITLE
Improve security + better support for newer Python versions

### ISSUE THREAD

**Issue by litios** [martinblech/xmltodict#321]
Hello,

Ubuntu is working to include xmltodict in our next release. As part of the "main inclusion review" (MIR) process to add software to our main package repository, we perform security audits. You can find the full xmltodict MIR bug report [here](https://bugs.launchpad.net/ubuntu/+source/python-xmltodict/+bug/2002576)

While auditing it, we found that the library is vulnerable to [typical XML attacks](https://docs.python.org/3/library/xml.html#xml-vulnerabilities) due to relying on expat as defusedexpat doesn't have support since 2016 and only up to Python 3.4.

In newer versions of expat these issues seem to be mitigated:
> Expat 2.4.1 and newer is not vulnerable to the “billion laughs” and “quadratic blowup” vulnerabilities. Items still listed as vulnerable due to potential reliance on system-provided libraries. Check pyexpat.EXPAT_VERSION.

but it still affects not so older python versions like 3.8

As recommended [by the documentation](https://docs.python.org/3/library/xml.html#the-defusedxml-package), there is currently a supported alternative called [defusedxml](https://github.com/tiran/defusedxml) owned by the same maintainer that owned defusedexpat.

It would be very beneficial to replace the old `defusedexpat` with `defusedxml`. Does that sound like something that could be valuable to the library and the users?

Thanks in advance!

**Comment by Murplugg** [comment]
Would love to see that.

**Comment by martinblech** [comment]
@litios this sounds indeed like a valuable contribution for the library and the users. I would be more than happy to review and approve such PR.

**Comment by litios** [comment]
The main idea was to point out that, right now, vulnerable Python versions won't have a safe alternative for untrusted input to known attacks. If running modern patched Python versions, you should be safe with expat.

Python 3.8, for example, is no longer affected since v3.8.12 but older 3.8 versions will be affected. Same for Python 3.7. And Python3.8 won't be out of support until the _end_ of 2024. 

And I agree that you will still need to enable allowing entities for attacks like billion laughs to work. I simply wanted to point out that defusedxml could be a good alternative to the old defusexpat meanwhile there are vulnerable Python expat versions out there.

**Comment by litios** [comment]
@martinblech I don't have the bandwidth right now to provide a PR for this. But I still wanted to raise the issue, just in case someone else wants to implement it in the meantime.

**Comment by hartwork** [comment]
> Python 3.8, for example, is no longer affected since v3.8.12 but older 3.8 versions will be affected. Same for Python 3.7. And Python3.8 won't be out of support until the _end_ of 2024.

@litios I think there may be a misunderstanding here, let's find out and be sure. To my understanding Python 3.8 being supported means that that the CPython project continues to do new 3.8.x releases with security fixes and that users can expected to be safe and receive updates *if* they run the latest 3.8.x version at any point in time, e.g. version 3.8.16 as of today. If someone is running say 3.8.8 today, they are using a supported track of the language but cannot expect to be secure. As a result, users running vanilla 3.8.x <=3.8.15 (meaning without backports) need to update their CPython and do not need any particular concern here. Does that sound correct?

**Comment by litios** [comment]
@hartwork yes, I totally agree. I'm sorry if what I wrote was unclear. Thanks for clarifying it!

**Comment by hannob** [comment]
Just to summarize this issue, as I think this can confuse others who might find this report: There is no security problem with currently supported versions of expat and python.

The security issues that were mitigated by defusedexpat are issues in older, unsupported versions of expat and python. I have therefore created a PR to remove the obsolete use of defusedexpat.

**Comment by hannob** [comment]
I think this can be closed now.

**Comment by tapple-cisco** [comment]
xmltodict 1.0.2 changed this behavior. It is still secure against entity venerabilities, but it now fails rather than ignores:

```
>>> import xmltodict
>>> xmltodict.parse("""<!DOCTYPE external [<!ENTITY ee SYSTEM "http://www.python.org/some.xml">]><root>&ee;</root>""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mfulmer\cabbage\typeshed\.venv\Lib\site-packages\xmltodict.py", line 368, in parse
    parser.Parse(xml_input, True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\AppData\Local\Temp\python-build-tg_pstd8\Python-3.13.1\Modules\pyexpat.c", line 510, in EntityDecl
  File "C:\Users\mfulmer\cabbage\typeshed\.venv\Lib\site-packages\xmltodict.py", line 358, in _forbid_entities
    raise ValueError("entities are disabled")
ValueError: entities are disabled

>>> xmltodict_parse("""<!DOCTYPE bomb [<!ENTITY a "xyz">]><bomb>&a;&a;&a;</bomb>""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'xmltodict_parse' is not defined

>>> xmltodict.parse("""<!DOCTYPE bomb [<!ENTITY a "xyz">]><bomb>&a;&a;&a;</bomb>""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mfulmer\cabbage\typeshed\.venv\Lib\site-packages\xmltodict.py", line 368, in parse
    parser.Parse(xml_input, True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\AppData\Local\Temp\python-build-tg_pstd8\Python-3.13.1\Modules\pyexpat.c", line 510, in EntityDecl
  File "C:\Users\mfulmer\cabbage\typeshed\.venv\Lib\site-packages\xmltodict.py", line 358, in _forbid_entities
    raise ValueError("entities are disabled")
ValueError: entities are disabled

>>> xmltodict.parse("<e>&lt;&quot;&#x48;&#x65;&#x6c;&#108;&#111;&#34;&gt;</e>")
{'e': '<"Hello">'}
```
