### ISSUE TITLE
Issue with python 3.5.3

### ISSUE THREAD

**Issue by kiferrara** [martinblech/xmltodict#360]
Hello, I'm having the following error in my program using the 0.14.0 version. It worked well with the previous version but since yesterday, I have this error. The python version used in my program is the 3.5.3

```
import xmltodict
File "/usr/local/lib/python3.5/dist-packages/xmltodict.py", line 424
attr = 'xmlns{}'.format(f':{k}' if k else '')
                              ^
SyntaxError: invalid syntax
```

Is this python version still supported?

**Comment by martinblech** [comment]
Python < 3.6 is no longer supported (format strings were introduced in 3.6)
