### ISSUE TITLE
unparse handles lists incorrectly?

### ISSUE THREAD

**Issue by jillh510** [martinblech/xmltodict#43]
My Python object looks like so:
{'Response': {'@ErrorCode': '00', 'Versions': [{'Version': {'@Updated': u'2013-10-23T18:29:11', 'Basic': {'@MD5': u'a7674c694607b169e57593a4952ea26f'}}}, {'Version': {'@Updated': u'2013-10-23T18:55:53', 'Basic': {'@MD5': u'b50001ee638f7df058d2c5f9157c6e8a'}}}]}}

The resulting XML from 'unparse' puts an endtag for Versions after the first Version, then starts it again before the second list item.

Seems that "Versions" shouldn't be ended after the first "Version" object?

**Comment by brizjin** [comment]
Is there still there is no way to unparse list of dicts without duplicates? At least it should be parameter to change the way it make's xml. Thank you!

**Comment by RealHerter** [comment]
Any chance to have this revisited? We have the same issue here

**Comment by Berserker1523** [comment]
> Any chance to have this revisited? We have the same issue here

Me too

**Comment by nebriv** [comment]
Also having this issue...

**Comment by Berserker1523** [comment]
I fixed that, but I changed it to accomplish my needs, so the old way was deleted

**Comment by nebriv** [comment]
I ended up using dicttoxml.
