### ISSUE TITLE
Add option to supress xml declaration (snippet-mode?)

### ISSUE THREAD

**Issue by mmangione** [martinblech/xmltodict#55]
This module does a marvelous job of parsing and unparsing XML. However, when I unparse an ordereddict, I do not always need the version and encoding declaration.

<?xml version="1.0" encoding="utf-8"?>

For example, I am creating OrderedDicts from scratch and passing them to unparse. Since these are intended to be snippets instead of fully declared xml, I find myself manually postprocessing this to remove this declaration.

**Comment by megahall** [comment]
FYI I think I found a bug in this. If you pass something like so:

    {
        "@name": "dbl-test",
        "description": "dbl-test",
        "recurring": {
            "hourly": {
                "at": "00"
            }
        },
        "type": "ip",
        "url": "http://192.168.1.6:8080/pa-dbl.txt"
    }

It's not able to turn that into an "XML snippet" even when you have `full_document=False`.

**Comment by martinblech** [comment]
@megahall I think it's not a bug: you cannot have a XML document with more than one root node. You should wrap that dict inside another dict with a single key:

```python
{
    "root": {
        "@name": "dbl-test",
        "description": "dbl-test",
        "recurring": {
            "hourly": {
                "at": "00"
            }
        },
        "type": "ip",
        "url": "http://192.168.1.6:8080/pa-dbl.txt"
    }
}
```

Otherwise, what XML opening tag should the `@name` attribute belong to?
