### ISSUE TITLE
Ability to avoid <![CDATA[ and ]]> tags to be converted when unparsing

### ISSUE THREAD

**Issue by skela** [martinblech/xmltodict#57]
When programatically creating for example Android XML strings files using your library's unparse functionality the library converts "<![CDATA[" into "& lt;![CDATA["
and "]]>" into "]]& gt;" (Spaces added between for the two html entities so things show up)

I don't know about other xml readers, but the Android SDK's way of allowing developers to add string resources that contain HTML symbols etc is to use CDATA tags like that.
I.e. you wrap your html string in CDATA tags and the android sdk doesn't go crazy when trying to parse the xml.

This is the xml I want to construct:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
<string name="some_html"><![CDATA[<a href="http://www.space.com">Hi my name is Bob</a>]]></string>
</resources>
```

This is what I pass to unparse:

```
val = '<![CDATA[<a href="http://www.space.com">Hi my name is Bob</a>]]>'
strings = [{"@name": "some_html", "#text": val}]
xmld = {"resources": {"string": strings}}
xml = xmltodict.unparse(xmld, pretty=True)
```

And this is the result:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
<string name="some_html">&lt;![CDATA[&lt;a href="http://www.space.com"&gt;Hi my name is Bob&lt;/a&gt;]]&gt;</string>
</resources>
```

I can't find a way to tell unparse not to try anything fancy for this particular value, but no luck, and I can't see anything obvious in your samples. Is there a way to achieve what I'm trying to do here?

**Comment by chaak20** [comment]
I also have this problem using 0.10.1. I'm using the '#text' keyvalue in the input dict but xmltodict never writes the CDATA text string out in the xml.  I also resorted to adding it in myself as @skela.  When I try your fix, it still does not work.

>>> import xmltodict
>>> val = '<a href="http://www.space.com">Hi my name is Bob</a>'
>>> strings = [{"@name": "some_html", "#text": val}]
>>> xmld = {"resources": {"string": strings}}
>>> xml = xmltodict.unparse(xmld, pretty=True)
>>> xml
'<?xml version="1.0" encoding="utf-8"?>\n<resources>\n\t<string name="some_html">&lt;a href="http://www.space.com"&gt;Hi my name is Bob&lt;/a&gt;</string>\n</resources>'

How can I get the CDATA text <![CDATA[ at the beginning and ]]> at the end without the escapes ?

**Comment by martinblech** [comment]
It's just not possible to do this with xmltodict, it's not what the library is intended for.

**Comment by chaak20** [comment]
FWIW, I was able to accomplish what I needed with this change:

*** xmltodict.py.orig   2016-03-28 13:37:00.098508399 -0500
--- xmltodict.py        2016-03-28 16:11:52.053726618 -0500
***************
*** 362,368 ****
--- 362,371 ----
                    attr_prefix, cdata_key, depth+1, preprocessor,
                    pretty, newl, indent)
          if cdata is not None:
+             # Output the CDATA start/end tags explicity
+             content_handler._write(r"<![CDATA[")
              content_handler.characters(cdata)
+             content_handler._write(r"]]>")
          if pretty and children:
              content_handler.ignorableWhitespace(depth * indent)
          content_handler.endElement(key)

**Comment by chaak20** [comment]
I understand now that xmltodict notion of cdata is different from XML's notion of CDATA. The above hack simply does not work because any and all character data gets encapsulated by XML's CDATA strings.

The solution I found is to do the following:
- Encapsulate any user CDATA with the XML CDATA strings.
- Use xmltodict.unparse() to write the data to a string
- Use xml.sax.saxutils.unescape() to reconvert the entity references back.

Thanks again for writing this library module as I find it very useful.

**Comment by codingpy** [comment]
I think it is weird that `xmltodict.parse()` could only read the character data from `<![CDATA[...]]>` but could not do the reverse.

Maybe we could extend the `cdata_key` to handle these cases wherever we need the `CDATA` section? For example, if `cdata_key='##text'`, then the value should be wrapped with the `<![CDATA[...]]>`.

Or, maybe we could simply provide the user with an optional argument (e.g. `cdata_sect=[]`) of `xmltodict.unparse()`, so we could specify which nodes should be wrapped.

So, we could avoid all the character data being wrapped.

> I understand now that xmltodict notion of cdata is different from XML's notion of CDATA. The above hack simply does not work because any and all character data gets encapsulated by XML's CDATA strings.
> 
> The solution I found is to do the following:
> 
> * Encapsulate any user CDATA with the XML CDATA strings.
> * Use xmltodict.unparse() to write the data to a string
> * Use xml.sax.saxutils.unescape() to reconvert the entity references back.
> 
> Thanks again for writing this library module as I find it very useful.
