### ISSUE TITLE
Streaming mode: More elaboration would be great

### ISSUE THREAD

**Issue by kmonsoor** [martinblech/xmltodict#74]
The details on the "Stream mode" is quite skimpy. As handling huge files is quite a bit challenging, it would be great some more examples and parameter details. A lot of trial-and-error effort could be saved.

for example,

```
>>> def handle_artist(_, artist):
...     print artist['name']
...     return True
>>> 
>>> xmltodict.parse(GzipFile('discogs_artists.xml.gz'),
...     item_depth=2, item_callback=handle_artist)
A Perfect Circle
Fantômas
```

Who never worked with GZip module, it would be pretty tough to guess, from where **GzipFile** came from.

**Comment by alexgustafson** [comment]
+1 in 2018

I have a large XML that is not gzipped. Cant figure it out. I will try Gzipping the file just so I can use GzipFile as in the example.
