### ISSUE TITLE
Not handling nil values

### ISSUE THREAD

**Issue by arikscore** [martinblech/xmltodict#76]
when parsing a node with a nil value:
`<example xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true" />`

We get this result:
`OrderedDict([(u'@http://www.w3.org/2001/XMLSchema-instance:nil', u'true')])`

I think it should actually return None or something of that form.

**Comment by prateekm33** [comment]
Can we pass in a parser or handler function that allows us to deal with these nil values?

**Comment by vladox** [comment]
@prateekm33 https://stackoverflow.com/a/58312565/164374
