### ISSUE TITLE
Python 3 issue

### ISSUE THREAD

**Issue by jabbalaci** [martinblech/xmltodict#77]
Under Python 3.4.2 I get an error:

XML input:

```
<?xml version="1.0"?>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
```

Python snippet:

```
with open(xml_file) as f:
    d = xmltodict.parse(f, xml_attribs=True)
```

Error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/xmltodict.py", line 246, in parse
    parser.ParseFile(xml_input)
TypeError: read() did not return a bytes object (type=str)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./xml2json.py", line 27, in <module>
    print(convert(sys.argv[1]))
  File "./xml2json.py", line 17, in convert
    d = xmltodict.parse(f, xml_attribs=xml_attribs)
  File "/usr/lib/python3.4/site-packages/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
TypeError: '_io.TextIOWrapper' does not support the buffer interface
```

Under Python 2.7 this example works fine.

**Comment by kolis** [comment]
I stumbled upon the same problem.

Is binary mode really a good solution? Why would I need to open an xml-file as binary :/

I would like this issue reopened, and using the binary mode only as a temporary workaround.

**Comment by martinblech** [comment]
@kolis binary mode is the correct way to do this, not a workaround. The XML parser expects bytes as input and takes care of the conversion from bytes to unicode.

**Comment by kolis** [comment]
I still don't see why the parser should expect bytes, XML is text. It is not a big deal, but I am curious of the reasoning for this.

**Comment by martinblech** [comment]
I didn't make the parser, can't say. Try asking in stackoverflow.com, someone out there might know.
