### ISSUE TITLE
Stop Parsing at Some Level or Exclude Tags

### ISSUE THREAD

**Issue by beyondai** [martinblech/xmltodict#78]
The issue we have is that current xmltodict parsing breaks the original text. For example:
Input:
<code>
<ABSTRACT>
Born: 22 July 1992 Selena <KW>Gomez</KW>
is an American actress and singer who has been working in the industry for quite some time, but is best known for her role as Alex
</ABSTRACT>
</code
so the "KW" is a markup tag for import words
Desired output is:
Key: "abstract"
Value: "Born: 22 July 1992 Selena <KW>Gomez</KW>
is an American actress and singer who has been working in the industry for quite some time, but is best known for her role as Alex"
Then we can do further processing as needed.

However, currently xmltodict gives this result:
(u'ABSTRACT', OrderedDict([(u'KW', u'Gomez'), ('#text', u'Born: 22 July 1992 Selena  is an American actress and singer who has been working in the industry for quite some time, but is best known for her role as Alex')]))
It extracts "Gomez" from the original text and we can not recover its original position in the text.

Is there a way to address this kind of issue?

Thanks,

**Comment by martinblech** [comment]
Thank you for reporting this. It's a known issue, but still haven't figured out a practical way to solve it. Please have a look at #63.
