### ISSUE TITLE
Stop Parsing at Some Level or Exclude Tags

### ISSUE THREAD

**Issue by beyondai** [martinblech/xmltodict#79]
This is for better formatting before I saw your reply.
Sorry for the repost~

The issue I have is that current parsing breaks the original text. For example:

Input:
```xml
<ABSTRACT>
Born: 22 July 1992 Selena <KW>Gomez</KW>
is an American actress and singer who has been working in the industry for quite some time, but is       best known for her role as Alex
</ABSTRACT>
```
so the "KW" tag is a markup for import words
Desired output is:
```xml
Key: "abstract"
Value: "Born: 22 July 1992 Selena <KW>Gomez</KW>
is an American actress and singer who has been working in the industry for quite some time, but is best known for her role as Alex"
Then we can do further processing as needed.
```
However, currently xmltodict gives this result:
(u'ABSTRACT', OrderedDict([(u'KW', u'Gomez'), ('#text', u'Born: 22 July 1992 Selena  is an American actress and singer who has been working in the industry for quite some time, but is best known for her role as Alex')]))
It extracts "Gomez" from the original text and we can not recover its original position in the text.

Is there a way to address this kind of issue?

Thanks,

**Comment by martinblech** [comment]
No problem. Updated the description of issue #78 with the improved formatting.
