### ISSUE TITLE
Confusion using defaultdict as dict_constructor

### ISSUE THREAD

**Issue by carmstrong** [martinblech/xmltodict#83]
Hi folks,

I'm converting an XML document with a lot of optional children, and I'd rather not wrap all of my indexes in a `try` block to `except KeyError` and return an empty string. For example, I want:

```
res['foo']['bar']['might']['exist']
```

to simply return `''` instead of throwing a `KeyError`. 

What I'm really trying to achieve is for keys not found in the resulting dict to just be empty strings. I found the discussion over in #14 regarding Python's `defaultdict` and thought it was relevant, so I tried using it in my code:
```
res = xmltodict.parse(xml, dict_constructor=lambda *args, **kwargs: defaultdict(str, *args, **kwargs))
```

And it works quite well for values that are not in the resulting dict, but for values which are, I'm getting:
```
TypeError: list indices must be integers, not str
```

Perhaps this is confusion with Python, or maybe xmltodict, but from reading the defaultdict [documentation](https://docs.python.org/2/library/collections.html#collections.defaultdict) I thought that this default constructor only applies to *missing* values, not *all* values: "This method is called by the __getitem__() method of the dict class when the requested key is not found; whatever it returns or raises is then returned or raised by __getitem__().".

Could someone shed some light here? Thanks so much!

**Comment by martinblech** [comment]
This is not a `xmltodict` issue. Python dictionaries raise `KeyError` when you try to access a nonexistent key, that's just how they work, and I don't think `defaultdict` will help you either.

Maybe you could post this `res['foo']['bar']['might']['exist']` example in [Stackoverflow](http://stackoverflow.com), since this is more of a general Python question, perhaps you will get more help over there. Good luck!

**Comment by carmstrong** [comment]
Thanks @martinblech - I had actually posted the question there before trying `defaultdict` with xmltodict - http://stackoverflow.com/questions/28039608/python-getting-sub-dicts-in-dicts-dynamically

I'm afraid my elementary understanding of Python is failing me here - I'm not sure how using a string is giving me the same problems as using None. Anyhow, thanks for the quick reply and for the library. Once I get it working, it's exactly what I need!

**Comment by acz13** [comment]
Perhaps you could try
```
    try:
        return = res[foo][bar][might][exist]
    except KeyError:
        return ''
```

**Comment by carmstrong** [comment]
> Perhaps you could try

Yes, but I am calling this over 100 times in my model utility, so catching the error each time isn't realistic. I thought about writing a wrapper function which would handle this for me, but couldn't figure out how to pass the sub-key I'm interested in without evaluating it when I'm passing it (i.e. `foo.bar.might.exist`).
