### ISSUE TITLE
My output has random list element before OrderedDict... 

### ISSUE THREAD

**Issue by xtiansimon** [martinblech/xmltodict#84]
I'm experiencing some odd list elements randomly inserted in my xmltodict output. I'm working to parse xml data from Wikipedia into a dictionary, so I can extract content elements and return a .csv file. I found xmltodict on StackOv. Problem is my output has random list element before OrderedDict and it's messing up my searching the tree. 

I'm something of a forever noob programmer, so maybe I've done something wrong. To troubleshoot the problem I ended up trimming down the original XML file I was working with. You can see this in the XML file below. To keep it simple and not create a lot of ouput files, I simply sent the output of xmltodict to the screen. Once that was working,

    11 import xmltodict
    12 import os
    13 import sys
    14 infile = sys.argv[1]
    18 f = open(infile, 'r')
    20 FileDict = xmltodict.parse(f)
    22 print(FileDict)
    24 f.close()

I directed this to a new file on the command line (linux).
     $ python2 myparse.py meso.xml >> meso.dict

When my helper function kept failing, I started walking through the output from xmltodict, and manually breaking the lines so I could figure out what kind of loop structure I needed. (I've never worked with OrderedDict before.) That's when I found a list element which should be just an OrderedDict:

    (u'namespaces', OrderedDict([
                             (u'namespace', [OrderedDict([
                                            ^

I thought I might have accidentally added this element, so did everything again. Downloaded the content (Wikipedia Special Export), trimmed out 700k lines down to 60 by just including one `<revision>` block of XML. I even used my IDE's jump from the top `<page>` element to the closing tag on the bottom of the XML to make sure I didn't cut out something important (as well as I can tell, the wikimedia Special:Export XML output consists of 45 lines at the top and 2 end tags at the bottom with block after block of `<revision>`) 

When I realized this list element is not in the same place after the second try, I thought to post this here. Sorry for the long winded, untechnical explanation. 

XML: http://pastebin.com/vnMj3S1h
XMLTODICT: http://pastebin.com/azU78nq0

**Comment by martinblech** [comment]
I don't see an issue here, there's nothing random about it. The following XML:
```xml
<namespaces>
      <namespace key="-2" case="first-letter">Media</namespace>
      <namespace key="-1" case="first-letter">Special</namespace>
</namespaces>
```
Maps to a `dict` like this:
```python
{
    "namespaces": {
        "namespace: [{
            "key": "-2",
            "case": "first-letter",
            "#text": "Media"
        }, {
            "key": "-1",
            "case": "first-letter",
            "#text": "Special"
        }]
    }
}
```

**Comment by xtiansimon** [comment]
I'm sorry. I don't understand. Your output example uses dictionary elements, but that's not what is produced by the module. The output has the form: `(u'key', OrderedDict([ ...]))`. So as long as the result has the pattern of (key, ordereddict) then each nested ordered dict is trivial to access. However the addition of the list element, (key, [ ordereddict]) caused my helper to break early. The surprising thing was I've processed the text twice and this `[` appeared in two different places. Which is why I posted my method, in case this was possibly causing the random element appearance.

**Comment by martinblech** [comment]
@xtiansimon The only difference between `dict` and `OrderedDict` is that the latter preserves key insertion order while the former doesn't. We can safely ignore this here.

There is nothing random about this behavior, it's just a duplicate of issue #14. Please have a look there to see the discussion and some possible workarounds.

**Comment by xtiansimon** [comment]
sorry. my bad. I was editing my reply...
