### ISSUE TITLE
Improve security against maliciously constructed data

### ISSUE THREAD

**Issue by iyn** [martinblech/xmltodict#97]
**Problem**
`xmltodict` is Expat-based, which is not secure against maliciously constructed data (it's even mentioned on the package docs: https://docs.python.org/3.4/library/pyexpat.html). 

**Possible Solution**
There is a project that improves Expat security: `defusedexpat` (PyPI: https://pypi.python.org/pypi/defusedexpat/ Bitbucket: https://bitbucket.org/tiran/defusedexpat). Using it instead of regular Expat could resolve security issues.

**Potential problems with implementation**
At this point I haven't researched compatibility issues that may arise if `xmltodict` were to use `defusedexpat`. Will do this in the next few days.

**More information**
https://docs.python.org/3.4/library/xml.html
https://pypi.python.org/pypi/defusedxml/
https://pypi.python.org/pypi/defusedexpat/
https://en.wikipedia.org/wiki/Billion_laughs
https://msdn.microsoft.com/en-us/magazine/ee335713.aspx

Let me know if there's interest in solving this problem. Is somebody interested in forking the repo and implementing the solution or should I do this (I won't be able to work on this until next week)?

**Comment by iyn** [comment]
Just now I've read the source of xmltodict, and it seems that the author thought of this earlier and it's possible to use `defusedexpat`:

    import defusedexpat
    xmltodict.parse('<a>hello</a>', expat=defusedexpat.pyexpat)

So, the question is, why not make defusedexpat a default version of expat?

**Comment by martinblech** [comment]
@iyn The main reason back then was to avoid introducing an extra dependency. Now that I think about it better, maybe a good compromise would be to use `defusedexpat` if available and fall back to regular `expat` if not, and raise a security warning. What do you think of this as a default?

**Comment by iyn** [comment]
@martinblech Yeah, I think that would be good solution. Although I have a problem compiling `defusedexpat` for Python 3.4 (it works after commenting out some parts of the code, but it's 'hacky' and not a proper way) - I contacted the author with the question if he plans to officially support Python 3.4. 

So, I'm in favor for using `defusedexpat` as a default, but I'd wait for Python 3.4 support.

**Comment by martinblech** [comment]
@iyn I understand. Is there an open issue at `defusedexpat` about Python 3.4 support that we can link to? Please leave a comment if the author if they get back to you.

**Comment by iyn** [comment]
Sadly, I still didn't hear back from the `defusedexpat` author/maintainer. And it seems that he didn't enable issues on Bitbucket. 

I would suggest, that semi-solution could be just adding more visible info about `defusedexpat` in README and a note that it probably won't work on Python 3.4 for some time.
